# 2023-02-02

name: tfsec-01
# on: [push]
on:
  push:
    branches:
      # - main
      - nonexistent  # avoid triggering on main
jobs:
  TFSec-Terraform-Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - name: TFSec Scan
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: terraform-in-action/chapter1
          