# 2023-02-03

name: trivy-01-image
on:
  push:
    branches:
      # - main
      - nonexistent  # avoid triggering on main
jobs:
  scan:
    name: scan
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3
      - name: Trivy scanner in image mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: ubuntu:latest
          # format: 'sarif'
          # output: 'trivy-results.sarif'
          # ignore-unfixed: true
          # severity: 'CRITICAL'
      # Error: Advanced Security must be enabled for this repository to use code scanning
      # - name: Upload Trivy scan results to GitHub Security tab
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: 'trivy-results.sarif'
